name: meurpg
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.7
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.0
  http: ^1.2.1
  uuid: ^4.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  permission_handler: ^11.0.0
  geocoding: ^2.1.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/rpg_group.png
    - assets/images/avatar1.png

dependency_overrides:
  geolocator: ^11.0.0
