// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyHd3vqGKdJPFR159BKcyY396hnme_bwA',
    appId: '1:636104400182:web:5d9172ba1ec653dfd2e797',
    messagingSenderId: '636104400182',
    projectId: 'meurpg-6055d',
    authDomain: 'meurpg-6055d.firebaseapp.com',
    storageBucket: 'meurpg-6055d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMjOVEUHPDa5o0dkatvhFRCX9xgFEst-I',
    appId: '1:636104400182:android:12d4e94a1d700bb3d2e797',
    messagingSenderId: '636104400182',
    projectId: 'meurpg-6055d',
    storageBucket: 'meurpg-6055d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDft8eHibxwtm9EJUEnJwSnV3YPv_HzSQE',
    appId: '1:636104400182:ios:9f9366a31121887dd2e797',
    messagingSenderId: '636104400182',
    projectId: 'meurpg-6055d',
    storageBucket: 'meurpg-6055d.firebasestorage.app',
    iosBundleId: 'com.example.meurpg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDft8eHibxwtm9EJUEnJwSnV3YPv_HzSQE',
    appId: '1:636104400182:ios:9f9366a31121887dd2e797',
    messagingSenderId: '636104400182',
    projectId: 'meurpg-6055d',
    storageBucket: 'meurpg-6055d.firebasestorage.app',
    iosBundleId: 'com.example.meurpg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyHd3vqGKdJPFR159BKcyY396hnme_bwA',
    appId: '1:636104400182:web:b5650bd0c29fd75ed2e797',
    messagingSenderId: '636104400182',
    projectId: 'meurpg-6055d',
    authDomain: 'meurpg-6055d.firebaseapp.com',
    storageBucket: 'meurpg-6055d.firebasestorage.app',
  );
}
